[debug] [2020-04-17T23:41:34.312Z] ----------------------------------------------------------------------
[debug] [2020-04-17T23:41:34.314Z] Command:       /usr/local/bin/node /usr/local/bin/firebase init
[debug] [2020-04-17T23:41:34.314Z] CLI Version:   8.1.1
[debug] [2020-04-17T23:41:34.315Z] Platform:      linux
[debug] [2020-04-17T23:41:34.315Z] Node Version:  v12.16.2
[debug] [2020-04-17T23:41:34.315Z] Time:          Sat Apr 18 2020 00:41:34 GMT+0100 (British Summer Time)
[debug] [2020-04-17T23:41:34.315Z] ----------------------------------------------------------------------
[debug] [2020-04-17T23:41:34.315Z] 
[debug] [2020-04-17T23:41:34.320Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-04-17T23:41:34.336Z] Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (/usr/local/lib/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/googleauth.js:160:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async GoogleAuth.getClient (/usr/local/lib/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/googleauth.js:502:17)
    at async GoogleAuth.getAccessToken (/usr/local/lib/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/googleauth.js:524:24)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2020-04-17T23:44:20.792Z] ----------------------------------------------------------------------
[debug] [2020-04-17T23:44:20.794Z] Command:       /usr/local/bin/node /usr/local/bin/firebase init
[debug] [2020-04-17T23:44:20.795Z] CLI Version:   8.1.1
[debug] [2020-04-17T23:44:20.795Z] Platform:      linux
[debug] [2020-04-17T23:44:20.795Z] Node Version:  v12.16.2
[debug] [2020-04-17T23:44:20.795Z] Time:          Sat Apr 18 2020 00:44:20 GMT+0100 (British Summer Time)
[debug] [2020-04-17T23:44:20.796Z] ----------------------------------------------------------------------
[debug] [2020-04-17T23:44:20.796Z] 
[debug] [2020-04-17T23:44:20.800Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-04-17T23:44:20.816Z] Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (/usr/local/lib/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/googleauth.js:160:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async GoogleAuth.getClient (/usr/local/lib/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/googleauth.js:502:17)
    at async GoogleAuth.getAccessToken (/usr/local/lib/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/googleauth.js:524:24)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2020-04-17T23:44:44.492Z] ----------------------------------------------------------------------
[debug] [2020-04-17T23:44:44.494Z] Command:       /usr/local/bin/node /usr/local/bin/firebase use --add
[debug] [2020-04-17T23:44:44.494Z] CLI Version:   8.1.1
[debug] [2020-04-17T23:44:44.494Z] Platform:      linux
[debug] [2020-04-17T23:44:44.494Z] Node Version:  v12.16.2
[debug] [2020-04-17T23:44:44.495Z] Time:          Sat Apr 18 2020 00:44:44 GMT+0100 (British Summer Time)
[debug] [2020-04-17T23:44:44.495Z] ----------------------------------------------------------------------
[debug] [2020-04-17T23:44:44.495Z] 
[debug] [2020-04-17T23:44:44.500Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-04-17T23:44:44.520Z] Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (/usr/local/lib/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/googleauth.js:160:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async GoogleAuth.getClient (/usr/local/lib/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/googleauth.js:502:17)
    at async GoogleAuth.getAccessToken (/usr/local/lib/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/googleauth.js:524:24)
[error] 
[error] Error: An unexpected error has occurred.
